language: python
dist: xenial
python: 3.6
before_install:
  - sudo apt-get update
  - sudo apt-get install -y hunspell hunspell-fr-comprehensive
install:
  - pip install pospell "powrap>=0.3.0"
  - pospell --version
  - powrap --version
script:
  - powrap --check --quiet **/*.po
  - pospell -p dict -l fr_FR **/*.po
  - make CPYTHON_CLONE=/tmp/cpython/ COMMIT=796698adf
