language: python
dist: xenial
python: 3.7
before_install:
  - sudo apt-get update
  - sudo apt-get install -y hunspell hunspell-fr-comprehensive
install:
  - pip install pospell "powrap>=0.3.0"
  - pospell --version
  - powrap --version
script:
  - 'printf "%s\n" "$TRAVIS_COMMIT_RANGE"'
  - 'CHANGED_FILES="$(git diff --name-only $TRAVIS_COMMIT_RANGE | grep "\.po$")" ;:'
  - 'printf "%s files changed.\n" "$(printf "%s" "$CHANGED_FILES" | grep -c "po$")" ;:'
  - '[ -n "$CHANGED_FILES" ] && printf -- "- %s\n" $CHANGED_FILES ;:'
  - 'powrap --check --quiet *.po */*.po'
  - 'pospell -p dict -l fr_FR *.po */*.po'
  - 'make CPYTHON_CLONE=/tmp/cpython/ COMMIT=4d1abedce9422473af2ac78047e55cde73208208'
