language: python
python: 3.6
before_install:
  - sudo apt-get update
  - sudo apt-get install -y hunspell hunspell-fr-comprehensive
install:
  - pip install pospell
  - pospell --version
script:
  - pospell -p dict -l fr *.po c-api/*.po library/*.po distributing/*.po installing/*.po install/*.po howto/*.po tutorial/*.po using/*.po whatsnew/*.po
  - make CPYTHON_CLONE=/tmp/cpython/ BRANCH=3.7
