language: python
dist: xenial
python: 3.7
before_install:
  - sudo apt-get update
  - sudo apt-get install -y hunspell hunspell-fr-comprehensive
install:
  - pip install pospell "powrap>=0.3.0"
  - pospell --version
  - powrap --version
script:
  - CHANGED_FILES="$(git diff --name-only $TRAVIS_COMMIT_RANGE | grep '\.po$';:)"
  - 'printf "%s files changed.\n" "$(printf "%s" "$CHANGED_FILES" | wc -l)"'
  - 'printf -- "- %s\n" $CHANGED_FILES | grep -v "^- $"'
  - '[ -n "$CHANGED_FILES" ] && powrap --check --quiet $CHANGED_FILES || echo "Nothing to check"'
  - '[ -n "$CHANGED_FILES" ] && pospell -p dict -l fr_FR $CHANGED_FILES || echo "Nothing to check"'
  - '[ -n "$CHANGED_FILES" ] && make CPYTHON_CLONE=/tmp/cpython/ COMMIT=4d1abedce9422473af2ac78047e55cde73208208 || echo "Nothing to build"'
